[phases.setup]
nixPkgs = ["nodejs_18", "python313", "postgresql"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requriements.txt",
  "cd frontend && npm ci"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "gunicorn backend.minNow.minNow.wsgi:application --bind 0.0.0.0:$PORT"
